"""add datatime

Revision ID: 82227c4d86ed
Revises: d99e0e3ccde2
Create Date: 2018-07-01 10:44:54.088994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82227c4d86ed'
down_revision = 'd99e0e3ccde2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=True)
    op.drop_column('users', 'update_time')
    op.drop_column('users', 'create_time')
    # ### end Alembic commands ###
